# Generated by Django 3.1.4 on 2021-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия менеджера')),
                ('name', models.CharField(max_length=20, verbose_name='Имя менеджера')),
                ('name_second', models.CharField(max_length=20, verbose_name='Отчество менеджера')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес проживания')),
                ('data_of_hiring', models.DateField(verbose_name='Дата принятия на работу')),
            ],
            options={
                'verbose_name': 'Менежер',
                'verbose_name_plural': 'Менежеры',
            },
        ),
    ]
