# Generated by Django 3.1.4 on 2021-01-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('manager', '0001_initial'),
        ('purchaseDocument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='manager_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='goods_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.goods'),
        ),
    ]
