# Generated by Django 3.1.4 on 2020-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название товара')),
                ('category', models.CharField(max_length=50, verbose_name='Категория товара')),
                ('count', models.IntegerField(default=0, verbose_name='Количество доступного товара')),
                ('prise', models.IntegerField(default=0, verbose_name='Стоимость товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
